### ISSUE TITLE
Conda dependency seemingly installed but failed to build job environment

### ISSUE THREAD

**Issue by nirshahaf** [workflow4metabolomics/lcmsmatching#51]
Hello. Did anybody get this error:
**Conda dependency seemingly installed but failed to build job environment.**
??

From general Galaxy bug reports it seems to be related to the default behaviour of Conda with job environments which are taking long time to build (which might be the case here). However it's only a guess. Here it is in more detail:

_Traceback (most recent call last):
  File "/galaxy-central/lib/galaxy/jobs/runners/__init__.py", line 170, in prepare_job
    job_wrapper.prepare()
  File "/galaxy-central/lib/galaxy/jobs/__init__.py", line 971, in prepare
    self.dependency_shell_commands = self.tool.build_dependency_shell_commands(job_directory=self.working_directory)
  File "/galaxy-central/lib/galaxy/tools/__init__.py", line 1415, in build_dependency_shell_commands
    tool_instance=self
  File "/galaxy-central/lib/galaxy/tools/deps/__init__.py", line 112, in dependency_shell_commands
    return [dependency.shell_commands(requirement) for requirement, dependency in requirement_to_dependency.items()]
  File "/galaxy-central/lib/galaxy/tools/deps/resolvers/conda.py", line 392, in shell_commands
    self.build_environment()
  File "/galaxy-central/lib/galaxy/tools/deps/resolvers/conda.py", line 387, in build_environment
    raise DependencyException("Conda dependency seemingly installed but failed to build job environment.")
DependencyException: Conda dependency seemingly installed but failed to build job environment._

**Comment by pkrog** [comment]
Hi @nirshahaf , I don't know about this error, and to be frank I do not understand what is going on. However I have been warned of an issue with one of the dependencies of the tool, that does not install correctly (or not at all) with conda. I'm currently working on an upgrade of the tool, and hope it will solve issues.

@fgiacomoni , could you please look at PeakForest server API (i.e.: why it is not responding)? I need it in order to finalise my tests and submit a new version of the lcmsmatching tool.

**Comment by nirshahaf** [comment]
Hi @pkrog I see discussions which seem to be related to the same problem, see:

https://github.com/galaxyproject/galaxy/issues/3078
https://github.com/galaxyproject/galaxy/pull/3106

**Comment by fgiacomoni** [comment]
Hi @pkrog - Peakforest ws are now fixed (Thanks @npaulhe). But carefully using this beta resource. Metabohub executive board doesn't valid data. So, we will add a supplementary authentication system based on ldap (should be temp.)
